channels:
- conda-forge
dependencies:
- python=3.12.7
- pip<=25.3
- pip:
  - mlflow==2.19.0
  - cloudpickle==3.1.1
  - numpy==2.3.4
  - pandas==2.3.3
  - pyarrow==18.1.0
  - scikit-learn==1.6.1  # ⬅️ UBAH INI agar sama dengan versi scaler Anda
  - scipy==1.16.2
  - imbalanced-learn
  - joblib
name: mlflow-env
